services:
    DahRomy\Mvola\Factory\MVolaApiClientFactory: ~

    DahRomy\Mvola\Service\ApiClient\MVolaApiClientInterface:
        factory: ['@DahRomy\Mvola\Factory\MVolaApiClientFactory', 'create']
        arguments:
            $environment: '%mvola.environment%'
            $merchantNumber: '%mvola.merchant_number%'
            $companyName: '%mvola.company_name%'

    GuzzleHttp\ClientInterface:
        class: GuzzleHttp\Client
        arguments:
            - { retry_on_status: [429, 500, 502, 503, 504], max_retries: '%mvola.max_retries%', delay: '%mvola.retry_delay%' }

    DahRomy\Mvola\Service\Auth\MVolaAuthenticatorInterface:
        class: DahRomy\Mvola\Service\Auth\MVolaAuthenticator
        arguments:
            $client: '@GuzzleHttp\ClientInterface'
            $authUrl: '%mvola.auth_url%'
            $consumerKey: '%mvola.consumer_key%'
            $consumerSecret: '%mvola.consumer_secret%'
            $cache: '@cache.app'
            $cacheTtl: '%mvola.cache_ttl%'

    DahRomy\Mvola\Service\Transaction\MVolaTransactionServiceInterface:
        class: DahRomy\Mvola\Service\Transaction\MVolaTransactionService
        arguments:
            $apiClient: '@DahRomy\Mvola\Service\ApiClient\MVolaApiClientInterface'

    DahRomy\Mvola\Service\MVolaService:
        arguments:
            $apiClient: '@DahRomy\Mvola\Service\ApiClient\MVolaApiClientInterface'
            $authenticator: '@DahRomy\Mvola\Service\Auth\MVolaAuthenticatorInterface'
            $transactionService: '@DahRomy\Mvola\Service\Transaction\MVolaTransactionServiceInterface'
            $router: '@router'

    DahRomy\Mvola\Service\Callback\MVolaCallbackHandlerInterface:
        class: DahRomy\Mvola\Service\Callback\MVolaCallbackHandler
        arguments:
            $logger: '@logger'
            $eventDispatcher: '@event_dispatcher'

    DahRomy\Mvola\Controller\MVolaCallbackController:
        public: true
        autowire: true
        autoconfigure: true
        tags: [ 'controller.service_arguments' ]
